# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# database
spring.datasource.url=jdbc:postgresql://dpg-d7i9gvjeo5us73dsqpog-a:5432/online_fees_db
spring.datasource.username=online_fees_db_user
spring.datasource.password=dwugR5ESkzxlXHUMHLTWkBepikMXUanS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=always
server.error.include-stacktrace=always